language: node_js
node_js:
    - "15"
services:
  - mysql
# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test
# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS life_guard default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize sequelize-cli mysql2 -g
  - sequelize db:migrate
script:
  - echo "skipping tests"
# 在執行測試之前的指令
# before_script:
  
deploy:
  provider: heroku
  api_key:
    secure: DEmFIQ84VC/RVsN77uSpoq1i+h++NtLlNspwH2Au9IPHvftsVYggvc/dJAkD3LgBfYM26XZENvTvfvdp+jSoy+LJqvBydjnjTamfkM6YM6lrzAvJLaQq7PDVSfSAGtgFikmbGP6F1ZvDp5TOr75mPm+hWwAriCPZGHEWsHR2gvSW6VKueMWkuiVzDG/GSTw1RLFkwDNYi/GTURVxGLooxx9rj540JQx3wrmHXara3ewi2su4mlaPAi0YdUUB9IDfcgTqb76k4fYuHh2o1Mft2sKi5PdfDJmgz+et6L9wPxeJOqFwiAceMMkpSC3pwp/O0fPQLV6l3KoHNxlhnK/I/IFhXrsKREHY1PeuhY49Gxpfgfvhi0V5TMbSwq5MdW8j1dWzHY2qT3aDx+lWI6CBwfXLgh/kZqCI7xtehsumKH5c9KEU0l9/qm5ezcDIBJq8VnBys2KVp3YcbAJclF3ob4IoBJYQ/sWsQdj9JJJ3UTs9C6u0gYoOx1WQ0iMEYThw/CvjG1AP6q+gDD4WllGtANyUns1zAp/NzGcWjhO62b0f2mG6xNyrNKoI6nZo53+jLI4Mownk1sneIIgFQr8MxwXwNH+fg10yqTIcfoN2ZC0z/vNLx81m0pR04+tsz/CbbjzQDiNkyZkThcWUigUvSkz7mJgY4pIIqsDbwwaCR3c=
  app: lifeguard2021
  on:
    repo: c6arliec6en/lifeguard-backend-test
    branch: main