language: node_js
node_js:
    - "12"
services:
  - mysql
# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test
# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS life_guard default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize sequelize-cli mysql2 -g
  - sequelize db:migrate
script:
  - echo "skipping tests"
# 在執行測試之前的指令
# before_script:
  
deploy:
  provider: heroku
  api_key:
    secure: LTigduOAKJ6dOdvF5pgfCp1bBy4ffam8eOBBUnSPUkfcpuCWjreW5/MiSnJw+AgL9/CHIn6XmZftVI6kLCSoQLG0eswj85lNgm95zl/GcHg0G661iJN4TbYpSoQPMJMO7yKMJzQ4e4EZKKgmCPcL59qzuDygyAasqoPtPKq+1IBS6Y5eMEmoD3JK9e487K0lZ/0l+0reIkMAs6+pBAd0DCU5MLKxWE7TV+2VUgQuVLBQwHLnCd19t8vJAdiHPsAVNcAEBI7M0sP7UQNV/8XeKO3oCAoTPCUE1McuQf1zNeD/VHKxjL/0ia8+Ug0u6TWNxDyWI8cAQLvXx5WbDWtQlxO/pK03TpYImbxRSTE3YrUmQR1TtzCwxdP87fpNuOcWZl+gTJBAmrQRw76cXyNYoHp2W4jI2UD/BNBlO9U7pQpej7oddhCsemSp7Pc95C5sSOEMYLo3R8ZfAYOKRn0C+PMOsLZNsMNn/oD2JPSTs+ztYcNqxhPsbmr0hXEEpt9Gq5fripx+Ynwf2orNGa+Do+b2qI1pCOdufGCJFdZ2RJcixpweaKXSD+lw52pa2eSWBSv4wi1U0HgqAMj0CTR8fTcVPGL4c5E1mHzlydWLPzilebaokEp3a6WXQRe65ylS9n3lNMMs4o1NUl0jrmzosr35s97Y3HXgqIUoBO+spzs=
  app: lifeguard2021
  on:
    repo: c6arliec6en/lifeguard-backend-test
    branch: main
  skip_cleanup: 'true'