language: node_js
node_js:
    - "12"
services:
  - mysql
# 設定參數(Travis CI 會按照參數分別執行)
env:
  - NODE_ENV=test
# 在 install 前執行的指令
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS life_guard default character set utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize sequelize-cli mysql2 -g
  - sequelize db:migrate
script:
  - echo "skipping tests"
# 在執行測試之前的指令
# before_script:
  
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: 
    secure: EATafCW6awldWLsaX30D2zDeDS9yEDE64LNR1ZMID7qA0weMH2CUknks0gOX07epDyGKwiKB1xM1obg8mmARfUWXdQj7Wr8LcpmRaU+cg95X4NBtYempx/wIDnbWX3HOSerP/PRd+pjpasg1z6Fe5Tv1pCJf0MtmvnahpVw8xWOnRGgNOmEViiqR6qcGb8D4wUweO1U2kzELz7DLOSbUySdpJ32n/FwMxzhHqaHLioKkDq/gRZ93pA+0QID/G/yAn/jEwcw00NEAX7jbQ7rjHCeq7Xm5LO6HfHTFKM5n+uSsHwjO0tMAsQxKT3C8FcyvqWFmmIm2/Ubh9dx9gTUyNyO/0/ewbIR2D/u5KRIov8Pc3snfaxNkD5J2OX2YzopTo/TQlbL2rhwZMJGXkRGuoKLapGePvG6NswryUgJQrl9n21/HkiURCzBYtJXnz6tVeIu6oiLeKxl5mMtVRL0ZkSBomlM0mlZ6bGsswoYLzwJtQiaG3jIIDDFeFA3Zyg5yTt5TvvN4AClw4k2gSSvp7M/hcHPfFg/u6F3CzBvf5IFGVoCJwY77ISZ6GZAGDdugqRXip5fzLgrTqrC4Rh8H/QdZZfvGxDfYquLqoDKT6w8NTe4ndG9d/1IO65O8CL7/SavkB2AJCcgqRh7e/D7J10G4Cy5KlnVcJs8hPsSSAJw=
  app: lifeguard2021
  on:
    repo: c6arliec6en/lifeguard-backend-test
    branch: main